name: CI/CD

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run Test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/rtg_lms_test
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate 
          bundle exec rails test
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: test
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sample-blog-ror"
          heroku_email: "jimuel@tappollo.com"
      - name: DB Migration
        run: |
          heroku run bundle exec rake db:migrate
